on: ['push', 'pull_request']
jobs:
  osx_mdp_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install --upgrade pip
    - name: Setup
      run: pip install -e .
    - name: Run tests
      run: |
        python -m unittest discover -s testing/ -p "overcooked_test.py"
